--- #YAML:1.0
name:               File-Namaste
version:            0.15
abstract:           routines for NAMe-AS-TExt tags (V0.1)
author:
    - John A. Kunze <jak@ucop.edu>
license:            Apache2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::ANVL:    0.15
    File::ERC:     0.01
    File::Spec:    0
    File::Value:   0.15
    Getopt::Long:  0
    Pod::Usage:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
