--- #YAML:1.0
name:                File-Namaste
version:             0.25
abstract:            nam (command) and routines to manage NAMe-AS-TExt tags
license:             BSD
author:              
    - John A. Kunze <jak@ucop.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::OM:                      0.2
    File::Spec:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
